# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iCommGui.ui'
#
# Created: Sat Nov 26 07:52:51 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(881, 600)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.GraphicsView = CGraphicsView(self.centralwidget)
        self.GraphicsView.setProperty(_fromUtf8("cursor"), QtCore.Qt.ArrowCursor)
        self.GraphicsView.setMouseTracking(True)
        self.GraphicsView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.GraphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.GraphicsView.setBackgroundBrush(brush)
        self.GraphicsView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.GraphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.NonCosmeticDefaultPen|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.GraphicsView.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.GraphicsView.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.GraphicsView.setRubberBandSelectionMode(QtCore.Qt.IntersectsItemBoundingRect)
        self.GraphicsView.setObjectName(_fromUtf8("GraphicsView"))
        self.horizontalLayout.addWidget(self.GraphicsView)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuElements = QtGui.QMenu(self.menubar)
        self.menuElements.setEnabled(True)
        self.menuElements.setMouseTracking(True)
        self.menuElements.setObjectName(_fromUtf8("menuElements"))
        self.menuAmplifiers = QtGui.QMenu(self.menuElements)
        self.menuAmplifiers.setObjectName(_fromUtf8("menuAmplifiers"))
        self.menuConverters = QtGui.QMenu(self.menuElements)
        self.menuConverters.setObjectName(_fromUtf8("menuConverters"))
        self.menuFilters = QtGui.QMenu(self.menuElements)
        self.menuFilters.setObjectName(_fromUtf8("menuFilters"))
        self.menuCouplers = QtGui.QMenu(self.menuElements)
        self.menuCouplers.setObjectName(_fromUtf8("menuCouplers"))
        self.menuHybrids = QtGui.QMenu(self.menuElements)
        self.menuHybrids.setObjectName(_fromUtf8("menuHybrids"))
        self.menu1_x = QtGui.QMenu(self.menuHybrids)
        self.menu1_x.setObjectName(_fromUtf8("menu1_x"))
        self.menu2_x = QtGui.QMenu(self.menuHybrids)
        self.menu2_x.setObjectName(_fromUtf8("menu2_x"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.Python = QtGui.QDockWidget(MainWindow)
        self.Python.setMinimumSize(QtCore.QSize(78, 103))
        self.Python.setFloating(False)
        self.Python.setFeatures(QtGui.QDockWidget.DockWidgetClosable|QtGui.QDockWidget.DockWidgetMovable)
        self.Python.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.Python.setObjectName(_fromUtf8("Python"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.PyInterp = PyInterp(self.dockWidgetContents)
        self.PyInterp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.PyInterp.setObjectName(_fromUtf8("PyInterp"))
        self.horizontalLayout_3.addWidget(self.PyInterp)
        self.Python.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.Python)
        self.Inspector = QtGui.QDockWidget(MainWindow)
        self.Inspector.setFeatures(QtGui.QDockWidget.DockWidgetClosable)
        self.Inspector.setAllowedAreas(QtCore.Qt.RightDockWidgetArea)
        self.Inspector.setObjectName(_fromUtf8("Inspector"))
        self.Stack = QtGui.QWidget()
        self.Stack.setObjectName(_fromUtf8("Stack"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Stack)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Inspector.setWidget(self.Stack)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.Inspector)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionProgram = QtGui.QAction(MainWindow)
        self.actionProgram.setObjectName(_fromUtf8("actionProgram"))
        self.actionTab = QtGui.QAction(MainWindow)
        self.actionTab.setObjectName(_fromUtf8("actionTab"))
        self.actionL_Camp = QtGui.QAction(MainWindow)
        self.actionL_Camp.setObjectName(_fromUtf8("actionL_Camp"))
        self.actionLNA = QtGui.QAction(MainWindow)
        self.actionLNA.setObjectName(_fromUtf8("actionLNA"))
        self.actionReceiver = QtGui.QAction(MainWindow)
        self.actionReceiver.setObjectName(_fromUtf8("actionReceiver"))
        self.actionTWT = QtGui.QAction(MainWindow)
        self.actionTWT.setObjectName(_fromUtf8("actionTWT"))
        self.actionDown_Converter = QtGui.QAction(MainWindow)
        self.actionDown_Converter.setObjectName(_fromUtf8("actionDown_Converter"))
        self.actionUp_Converter = QtGui.QAction(MainWindow)
        self.actionUp_Converter.setObjectName(_fromUtf8("actionUp_Converter"))
        self.actionIMux = QtGui.QAction(MainWindow)
        self.actionIMux.setObjectName(_fromUtf8("actionIMux"))
        self.actionOMux = QtGui.QAction(MainWindow)
        self.actionOMux.setObjectName(_fromUtf8("actionOMux"))
        self.actionDirectional = QtGui.QAction(MainWindow)
        self.actionDirectional.setObjectName(_fromUtf8("actionDirectional"))
        self.actionTest_Coupler = QtGui.QAction(MainWindow)
        self.actionTest_Coupler.setObjectName(_fromUtf8("actionTest_Coupler"))
        self.actionAdapter = QtGui.QAction(MainWindow)
        self.actionAdapter.setObjectName(_fromUtf8("actionAdapter"))
        self.actionAttenuator = QtGui.QAction(MainWindow)
        self.actionAttenuator.setObjectName(_fromUtf8("actionAttenuator"))
        self.actionCirculators = QtGui.QAction(MainWindow)
        self.actionCirculators.setObjectName(_fromUtf8("actionCirculators"))
        self.actionCoax = QtGui.QAction(MainWindow)
        self.actionCoax.setObjectName(_fromUtf8("actionCoax"))
        self.actionIsolator = QtGui.QAction(MainWindow)
        self.actionIsolator.setObjectName(_fromUtf8("actionIsolator"))
        self.actionWaveguide = QtGui.QAction(MainWindow)
        self.actionWaveguide.setObjectName(_fromUtf8("actionWaveguide"))
        self.actionPython_Colsole = QtGui.QAction(MainWindow)
        self.actionPython_Colsole.setCheckable(True)
        self.actionPython_Colsole.setChecked(True)
        self.actionPython_Colsole.setObjectName(_fromUtf8("actionPython_Colsole"))
        self.actionObject_Inspector = QtGui.QAction(MainWindow)
        self.actionObject_Inspector.setCheckable(True)
        self.actionObject_Inspector.setObjectName(_fromUtf8("actionObject_Inspector"))
        self.action2_1 = QtGui.QAction(MainWindow)
        self.action2_1.setObjectName(_fromUtf8("action2_1"))
        self.action3_1 = QtGui.QAction(MainWindow)
        self.action3_1.setObjectName(_fromUtf8("action3_1"))
        self.action4_1 = QtGui.QAction(MainWindow)
        self.action4_1.setObjectName(_fromUtf8("action4_1"))
        self.action5_1 = QtGui.QAction(MainWindow)
        self.action5_1.setObjectName(_fromUtf8("action5_1"))
        self.action6_1 = QtGui.QAction(MainWindow)
        self.action6_1.setObjectName(_fromUtf8("action6_1"))
        self.action7_1 = QtGui.QAction(MainWindow)
        self.action7_1.setObjectName(_fromUtf8("action7_1"))
        self.action8_1 = QtGui.QAction(MainWindow)
        self.action8_1.setObjectName(_fromUtf8("action8_1"))
        self.action1_2 = QtGui.QAction(MainWindow)
        self.action1_2.setObjectName(_fromUtf8("action1_2"))
        self.action2_2 = QtGui.QAction(MainWindow)
        self.action2_2.setObjectName(_fromUtf8("action2_2"))
        self.action3_2 = QtGui.QAction(MainWindow)
        self.action3_2.setObjectName(_fromUtf8("action3_2"))
        self.action4_2 = QtGui.QAction(MainWindow)
        self.action4_2.setObjectName(_fromUtf8("action4_2"))
        self.action5_2 = QtGui.QAction(MainWindow)
        self.action5_2.setObjectName(_fromUtf8("action5_2"))
        self.action6_2 = QtGui.QAction(MainWindow)
        self.action6_2.setObjectName(_fromUtf8("action6_2"))
        self.action7_2 = QtGui.QAction(MainWindow)
        self.action7_2.setObjectName(_fromUtf8("action7_2"))
        self.action8_2 = QtGui.QAction(MainWindow)
        self.action8_2.setObjectName(_fromUtf8("action8_2"))
        self.menuNew.addAction(self.actionTab)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuAmplifiers.addAction(self.actionL_Camp)
        self.menuAmplifiers.addAction(self.actionLNA)
        self.menuAmplifiers.addAction(self.actionReceiver)
        self.menuAmplifiers.addAction(self.actionTWT)
        self.menuConverters.addAction(self.actionDown_Converter)
        self.menuConverters.addAction(self.actionUp_Converter)
        self.menuFilters.addAction(self.actionIMux)
        self.menuFilters.addAction(self.actionOMux)
        self.menuCouplers.addAction(self.actionDirectional)
        self.menuCouplers.addAction(self.actionTest_Coupler)
        self.menu1_x.addAction(self.action2_1)
        self.menu1_x.addAction(self.action3_1)
        self.menu1_x.addAction(self.action4_1)
        self.menu1_x.addAction(self.action5_1)
        self.menu1_x.addAction(self.action6_1)
        self.menu1_x.addAction(self.action7_1)
        self.menu1_x.addAction(self.action8_1)
        self.menu2_x.addAction(self.action1_2)
        self.menu2_x.addAction(self.action2_2)
        self.menu2_x.addAction(self.action3_2)
        self.menu2_x.addAction(self.action4_2)
        self.menu2_x.addAction(self.action5_2)
        self.menu2_x.addAction(self.action6_2)
        self.menu2_x.addAction(self.action7_2)
        self.menu2_x.addAction(self.action8_2)
        self.menuHybrids.addAction(self.menu1_x.menuAction())
        self.menuHybrids.addAction(self.menu2_x.menuAction())
        self.menuElements.addAction(self.menuAmplifiers.menuAction())
        self.menuElements.addAction(self.menuConverters.menuAction())
        self.menuElements.addAction(self.menuFilters.menuAction())
        self.menuElements.addAction(self.menuHybrids.menuAction())
        self.menuElements.addAction(self.menuCouplers.menuAction())
        self.menuElements.addSeparator()
        self.menuElements.addAction(self.actionAdapter)
        self.menuElements.addAction(self.actionAttenuator)
        self.menuElements.addAction(self.actionCirculators)
        self.menuElements.addAction(self.actionCoax)
        self.menuElements.addAction(self.actionIsolator)
        self.menuElements.addAction(self.actionWaveguide)
        self.menuView.addAction(self.actionPython_Colsole)
        self.menuView.addAction(self.actionObject_Inspector)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuElements.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.menubar, QtCore.SIGNAL(_fromUtf8("triggered(QAction*)")), MainWindow.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.menuElements.setTitle(QtGui.QApplication.translate("MainWindow", "Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAmplifiers.setTitle(QtGui.QApplication.translate("MainWindow", "Amplifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConverters.setTitle(QtGui.QApplication.translate("MainWindow", "Converters", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFilters.setTitle(QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCouplers.setTitle(QtGui.QApplication.translate("MainWindow", "Couplers", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHybrids.setTitle(QtGui.QApplication.translate("MainWindow", "Hybrids", None, QtGui.QApplication.UnicodeUTF8))
        self.menu1_x.setTitle(QtGui.QApplication.translate("MainWindow", "1:x", None, QtGui.QApplication.UnicodeUTF8))
        self.menu2_x.setTitle(QtGui.QApplication.translate("MainWindow", "2:x", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.Python.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Python Interpreter", None, QtGui.QApplication.UnicodeUTF8))
        self.Inspector.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Object Inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProgram.setText(QtGui.QApplication.translate("MainWindow", "Program", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTab.setText(QtGui.QApplication.translate("MainWindow", "Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionL_Camp.setText(QtGui.QApplication.translate("MainWindow", "L-Camp", None, QtGui.QApplication.UnicodeUTF8))
        self.actionL_Camp.setShortcut(QtGui.QApplication.translate("MainWindow", "Meta+Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLNA.setText(QtGui.QApplication.translate("MainWindow", "LNA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLNA.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReceiver.setText(QtGui.QApplication.translate("MainWindow", "Receiver", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReceiver.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTWT.setText(QtGui.QApplication.translate("MainWindow", "TWT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTWT.setShortcut(QtGui.QApplication.translate("MainWindow", "Meta+Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDown_Converter.setText(QtGui.QApplication.translate("MainWindow", "Down Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDown_Converter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUp_Converter.setText(QtGui.QApplication.translate("MainWindow", "Up Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUp_Converter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+U", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIMux.setText(QtGui.QApplication.translate("MainWindow", "IMux", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOMux.setText(QtGui.QApplication.translate("MainWindow", "OMux", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDirectional.setText(QtGui.QApplication.translate("MainWindow", "Directional", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Coupler.setText(QtGui.QApplication.translate("MainWindow", "Test Coupler", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdapter.setText(QtGui.QApplication.translate("MainWindow", "Adapter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAttenuator.setText(QtGui.QApplication.translate("MainWindow", "Attenuator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCirculators.setText(QtGui.QApplication.translate("MainWindow", "Circulators", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoax.setText(QtGui.QApplication.translate("MainWindow", "Coax", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIsolator.setText(QtGui.QApplication.translate("MainWindow", "Isolator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWaveguide.setText(QtGui.QApplication.translate("MainWindow", "Waveguide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_Colsole.setText(QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_Colsole.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObject_Inspector.setText(QtGui.QApplication.translate("MainWindow", "Object Inspector", None, QtGui.QApplication.UnicodeUTF8))
        self.actionObject_Inspector.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.action2_1.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.action3_1.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.action4_1.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.action5_1.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.action6_1.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.action7_1.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.action8_1.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.action1_2.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.action2_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.action3_2.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.action4_2.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.action5_2.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.action6_2.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.action7_2.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.action8_2.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))

from cgraphicsview import CGraphicsView
from Python_Interpreter.pyinterp import PyInterp
